dist: bionic
language: java
jdk:
  # JDK 8 not supported any more: - openjdk8
  - openjdk11

env:
  global:
    - RUNNING_IN_TRAVIS="true"

before_install:
 - chmod +x gradlew gradle/wrapper/gradle-wrapper.jar
 - git fetch --unshallow

install: 
- gradle wrapper
- ./gradlew compileJava

after_success:
- ./gradlew jacocoTestReport

after_failure:
- cat build/test-results/test/*.xml
