language: java
jdk:
# started to fail, replace by openjdk8  - oraclejdk8
  - openjdk8
  - oraclejdk11
# not available yet  - openjdk11

env:
  global:
    - RUNNING_IN_TRAVIS="true"

before_install:
 - chmod +x gradlew
 - git fetch --unshallow

after_success:
- ./gradlew jacocoTestReport

after_failure:
- cat build/test-results/test/*.xml
