language: java
jdk:
  - oraclejdk8

env:
  global:
    - RUNNING_IN_TRAVIS="true"

before_install:
 - chmod +x gradlew
 - git fetch --unshallow

after_success:
- ./gradlew jacocoTestReport

after_failure:
- cat build/test-results/*.xml
